# Generated by Django 4.0.6 on 2022-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mylog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField(auto_now_add=True)),
                ('mood', models.SmallIntegerField(choices=[(0, '매우 나쁨'), (1, '나쁨'), (2, '보통'), (3, '좋음'), (4, '매우 좋음')], default=2)),
                ('learned', models.TextField()),
                ('lacked', models.TextField()),
                ('improve', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='log_photo')),
            ],
        ),
    ]
