# Generated by Django 4.0.6 on 2022-07-28 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0003_mylog_log_date2_alter_mylog_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 18, 57, 5, 721231)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mylog_photo'),
        ),
    ]
