# Generated by Django 4.0.6 on 2022-08-04 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0006_mylog_video_alter_mylog_log_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylog',
            name='log_date',
        ),
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 22, 13, 47, 785985)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mood',
            field=models.TextField(choices=[('0', '&#128545;'), ('1', '&#128533;'), ('2', '&#128528;'), ('3', '&#128578;'), ('4', '&#128540;')], default='&#128528;'),
        ),
    ]
