# Generated by Django 4.0.6 on 2022-08-04 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0007_remove_mylog_log_date_alter_mylog_log_date2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 4, 22, 36, 49, 958826)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mood',
            field=models.TextField(choices=[(0, '😡'), (1, '😕'), (2, '😐'), (3, '🙂'), (4, '😜')], default='&#128528;'),
        ),
    ]
