# Generated by Django 4.0.6 on 2022-08-05 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0008_alter_mylog_log_date2_alter_mylog_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='improve',
            field=models.TextField(default='개선할점'),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='lacked',
            field=models.TextField(default='부족한점'),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='learned',
            field=models.TextField(default='배운점'),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 5, 18, 1, 492300)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mood',
            field=models.TextField(default='😐'),
        ),
    ]
