# Generated by Django 4.0.6 on 2022-07-30 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0008_alter_mylog_log_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 16, 18, 41, 977860)),
        ),
    ]
