# Generated by Django 4.0.6 on 2022-08-05 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0009_alter_mylog_improve_alter_mylog_lacked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 6, 48, 34, 937112)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mood',
            field=models.TextField(choices=[(0, '😡'), (1, '😕'), (2, '😐'), (3, '🙂'), (4, '😜')], default='😐'),
        ),
    ]
