# Generated by Django 4.0.6 on 2022-08-05 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0011_alter_mylog_improve_alter_mylog_lacked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 6, 54, 43, 191539)),
        ),
        migrations.AlterField(
            model_name='mylog',
            name='mood',
            field=models.TextField(choices=[('😡', '😡'), ('😕', '😕'), ('😐', '😐'), ('🙂', '🙂'), ('😜', '😜')], default='😐'),
        ),
    ]
