# Generated by Django 4.0.6 on 2022-08-05 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylog', '0012_alter_mylog_log_date2_alter_mylog_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylog',
            name='log_date2',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 8, 0, 53, 510998)),
        ),
    ]
