# Generated by Django 4.0.4 on 2022-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저', 'verbose_name_plural': '유저'},
        ),
        migrations.AddField(
            model_name='user',
            name='userid',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='userid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_register_dttm',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='signupdate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
