# Generated by Django 4.0.4 on 2022-07-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_userid_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='user_id'),
        ),
    ]
