# Generated by Django 4.0.6 on 2022-08-11 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime(2022, 8, 11, 14, 57, 39, 735393))),
                ('tag', models.TextField(choices=[('긴급', '긴급'), ('일반', '일반'), ('훈련', '훈련')], default='일반')),
                ('contents', models.TextField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mylog_photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='mylog_file')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 14, 57, 39, 735393))),
                ('location', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateField(default=datetime.datetime(2022, 8, 11, 14, 57, 39, 735393))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mylog_photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='mylog_file')),
                ('contents', models.TextField()),
            ],
        ),
    ]
