# Generated by Django 4.0.4 on 2022-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tactic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tactic_file'),
        ),
    ]
