# Generated by Django 4.0.6 on 2022-08-11 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0002_alter_notice_date_alter_notice_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 15, 5, 37, 459373)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 15, 5, 37, 459373)),
        ),
        migrations.AlterField(
            model_name='notice',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notice_photo'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='notice_file'),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 15, 5, 37, 458384)),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tactic_photo'),
        ),
        migrations.AlterField(
            model_name='tactic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tactic_file'),
        ),
    ]
