# Generated by Django 4.0.4 on 2022-08-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realjoinpw', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
