# Generated by Django 4.0.6 on 2022-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myteam', '0001_initial'),
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='notices',
            field=models.ManyToManyField(blank=True, related_name='Notice', to='myteam.notice'),
        ),
        migrations.AddField(
            model_name='team',
            name='tactics',
            field=models.ManyToManyField(blank=True, related_name='Tactic', to='myteam.tactic'),
        ),
    ]
