# Generated by Django 4.0.4 on 2022-08-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='join',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='jointeam_photo'),
        ),
        migrations.AddField(
            model_name='join',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
