# Generated by Django 4.0.4 on 2022-08-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_join_photo_join_subtitle_alter_join_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='photo',
            field=models.ImageField(null=True, upload_to='jointeam_photo'),
        ),
    ]
