# Generated by Django 4.0.4 on 2022-08-19 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_realjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealPwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realpwd', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(upload_to='jointeam_photo'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=10, null=True)),
                ('real', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='join.realpwd')),
            ],
        ),
    ]
