# Generated by Django 4.0.4 on 2022-08-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_joinpass_alter_join_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinPass',
        ),
        migrations.AddField(
            model_name='join',
            name='joinpw',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
